# Generated by Django 5.2.13 on 2026-05-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0026_fuzzy_match_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsnapshot',
            name='has_coi_policy',
            field=models.BooleanField(blank=True, help_text='Part VI Line 12a — conflict of interest policy exists', null=True),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='has_document_retention_policy',
            field=models.BooleanField(blank=True, help_text='Part VI Line 14 — document retention policy exists', null=True),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='has_whistleblower_policy',
            field=models.BooleanField(blank=True, help_text='Part VI Line 13 — whistleblower policy exists', null=True),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='related_party_disclosed',
            field=models.BooleanField(blank=True, help_text='Part IV Line 28 — org had related-party transactions (schedule_l_required)', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='formation_date',
            field=models.DateField(blank=True, help_text='Date the entity was legally formed per Secretary of State records.', null=True),
        ),
    ]
