# Generated by Django 5.2.13 on 2026-05-17 04:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0027_governance_fields_financialsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(help_text='Display order within the case (1-based, investigator-assigned)')),
                ('question', models.TextField(help_text='The question that triggered this investigation step')),
                ('source', models.CharField(blank=True, default='', help_text="Source consulted — e.g. 'IRS TEOS', 'Ohio SOS', 'County Recorder'", max_length=200)),
                ('what_was_found', models.TextField(blank=True, default='', help_text='Narrative of what was discovered at this step')),
                ('who_originated', models.CharField(choices=[('T', 'Tyler'), ('C', 'Claude'), ('X', 'External tip')], default='T', help_text='T = Tyler, C = Claude, X = External tip', max_length=10)),
                ('triggered_question', models.CharField(blank=True, default='', help_text='The follow-on question this step opened', max_length=500)),
                ('status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('OPEN', 'Open'), ('DEAD_END', 'Dead end')], default='RESOLVED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_steps', to='investigations.case')),
                ('triggered_finding', models.ForeignKey(blank=True, help_text='Angle (Finding) this step produced, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_steps', to='investigations.finding')),
            ],
            options={
                'db_table': 'investigation_steps',
                'ordering': ['step_number'],
                'indexes': [models.Index(fields=['case', 'step_number'], name='idx_inv_step_case_num')],
            },
        ),
    ]
