# Generated by Django 5.2.13 on 2026-05-17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigations", "0028_investigationstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(
                        help_text=(
                            "Name of the receiving agency "
                            "(e.g. 'Ohio AG — Charitable Law Section')"
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Type of complaint filed "
                            "(e.g. 'Charitable fraud', 'Tax-exempt complaint')"
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agency-assigned reference or complaint number",
                        max_length=100,
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact name or unit at the receiving agency",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about this referral",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_targets",
                        to="investigations.case",
                    ),
                ),
            ],
            options={
                "db_table": "referral_targets",
                "ordering": ["created_at"],
            },
        ),
    ]
