# Generated by Django 5.2.13 on 2026-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0029_referraltarget'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referraltarget',
            constraint=models.UniqueConstraint(fields=('case', 'agency_name'), name='uniq_referral_target_case_agency'),
        ),
    ]
