# Generated by Django 5.2.13 on 2026-05-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0030_referraltarget_unique_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='ai_run',
            field=models.ForeignKey(blank=True, help_text='SearchJob (AI_PATTERN_ANALYSIS) that produced this finding. Populated only when source=AI. Links the finding back to the exact job ID and model version for chain-of-custody.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_findings', to='investigations.searchjob'),
        ),
        migrations.AddField(
            model_name='finding',
            name='narrative_source',
            field=models.CharField(choices=[('HUMAN', 'Human-authored'), ('AI_DRAFT', 'AI draft — not yet reviewed by investigator'), ('AI_ASSISTED', 'AI-assisted — investigator edited the AI draft')], default='HUMAN', help_text='Who authored the current narrative text. Transitions: AI_DRAFT → AI_ASSISTED when investigator edits without explicitly overriding the source label.', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='narrative_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent narrative write (human or AI).', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_INGESTED', 'Document ingested'), ('DOCUMENT_SCRUBBED', 'Document metadata scrubbed'), ('DOCUMENT_HASHED', 'Document hash computed'), ('DOCUMENT_HASH_VERIFIED', 'Document hash re-verified'), ('DOCUMENT_HASH_MISMATCH', 'Document hash mismatch detected'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_OCR_COMPLETED', 'Document OCR completed'), ('DOCUMENT_OCR_FAILED', 'Document OCR failed'), ('RECORD_CREATED', 'Record created'), ('RECORD_UPDATED', 'Record updated'), ('RECORD_DELETED', 'Record deleted'), ('SIGNAL_DETECTED', 'Signal detected'), ('SIGNAL_CONFIRMED', 'Signal confirmed'), ('SIGNAL_DISMISSED', 'Signal dismissed'), ('SIGNAL_ESCALATED', 'Signal escalated to finding'), ('FINDING_CREATED', 'Finding created'), ('FINDING_UPDATED', 'Finding updated'), ('FINDING_INCLUDED', 'Finding included in memo'), ('REFERRAL_CREATED', 'Referral created'), ('REFERRAL_SUBMITTED', 'Referral submitted'), ('REFERRAL_STATUS_CHANGED', 'Referral status changed'), ('INTAKE_REJECTED_SIZE', 'File rejected — exceeds size limit'), ('INTAKE_REJECTED_TYPE', 'File rejected — invalid MIME type'), ('INTAKE_REJECTED_CORRUPT', 'File rejected — corrupted or unreadable'), ('HASH_VERIFICATION_BATCH', 'Batch hash verification completed'), ('AI_EXTRACTION_COMPLETED', 'AI extraction completed on document'), ('AI_EXTRACTION_FAILED', 'AI extraction failed on document'), ('AI_PATTERN_RUN_COMPLETED', 'AI pattern analysis run completed'), ('AI_FINDING_CREATED', 'AI-flagged pattern written as finding'), ('AI_FINDING_REVIEWED', 'Investigator reviewed an AI-flagged finding')], help_text='Constrained action type — use AuditAction enum values only.', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('CHARITY', 'Charity / 501(c)(3)'), ('LLC', 'LLC'), ('CORPORATION', 'Corporation'), ('LLP', 'Limited Liability Partnership'), ('PARTNERSHIP', 'General Partnership'), ('SOLE_PROP', 'Sole Proprietorship'), ('LAND_TRUST', 'Land Trust'), ('FARM_LLC', 'Farm / Agricultural LLC'), ('HMAIN', 'Holding Company'), ('FILM_PROD', 'Film / Media Production'), ('GOVERNMENT', 'Government'), ('CIC', 'CIC'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
