# Generated by Django 5.2.13 on 2026-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0031_ai_traceability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchjob',
            name='job_type',
            field=models.CharField(choices=[('IRS_NAME_SEARCH', 'IRS Name Search'), ('IRS_FETCH_XML', 'IRS Fetch XML'), ('OHIO_AOS', 'Ohio Auditor of State'), ('COUNTY_PARCEL', 'County Parcel Search'), ('AI_PATTERN_ANALYSIS', 'AI Pattern Analysis'), ('AI_ASK', 'AI Ask Question')], max_length=32),
        ),
    ]
