# Generated by Django 5.2.13 on 2026-05-27 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0032_add_ai_ask_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsnapshot',
            name='schedule_o_explanations',
            field=models.JSONField(blank=True, default=list, help_text="Schedule O supplemental explanations from IRS XML. List of dicts: [{form_line_reference, explanation_text}] Contains the org's own written disclosures — most candid text on the filing."),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='schedule_r_orgs',
            field=models.JSONField(blank=True, default=list, help_text='Schedule R related organizations extracted from IRS XML. List of dicts: [{name, ein, org_type, description}]'),
        ),
        migrations.CreateModel(
            name='ScheduleLTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_year', models.IntegerField(help_text='Denormalized from snapshot.tax_year for query convenience.')),
                ('party_name', models.CharField(help_text='Name of the interested person as listed on Schedule L.', max_length=500)),
                ('relationship_description', models.TextField(blank=True, default='', help_text='Relationship to the org (e.g. "officer", "family member of director").')),
                ('transaction_description', models.TextField(blank=True, default='', help_text="What the transaction was (e.g. 'Lease agreement', 'Loan').")),
                ('amount', models.BigIntegerField(blank=True, help_text='Dollar amount of the transaction. Nullable — some Schedule L entries omit it.', null=True)),
                ('case', models.ForeignKey(help_text='Denormalized from snapshot.case for direct case-level queries without an extra join through FinancialSnapshot.', on_delete=django.db.models.deletion.RESTRICT, related_name='schedule_l_transactions', to='investigations.case')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_l_transactions', to='investigations.financialsnapshot')),
            ],
            options={
                'db_table': 'schedule_l_transactions',
                'indexes': [models.Index(fields=['case'], name='idx_sched_l_case'), models.Index(fields=['snapshot'], name='idx_sched_l_snapshot'), models.Index(fields=['amount'], name='idx_sched_l_amount')],
            },
        ),
    ]
