# Generated by Django 5.2.13 on 2026-05-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0033_schedule_l_transaction_and_snapshot_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleltransaction',
            options={'ordering': ['tax_year', 'party_name']},
        ),
        migrations.AlterField(
            model_name='scheduleltransaction',
            name='tax_year',
            field=models.IntegerField(help_text='Denormalized from snapshot.tax_year for query convenience. Must be set to snapshot.tax_year at creation time — not automatically synced.'),
        ),
    ]
