# Generated by Django 5.2.15 on 2026-06-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0034_alter_scheduleltransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsnapshot',
            name='source',
            field=models.CharField(default='EXTRACTED', help_text='EXTRACTED (from document OCR), IRS_TEOS_XML (TEOS pipeline), MANUAL', max_length=20),
        ),
    ]
