# Generated by Django 5.2.15 on 2026-06-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0034_alter_scheduleltransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='overreach_reviewed',
            field=models.BooleanField(default=False, help_text='Investigator acknowledged the overreach checklist at tie-off. The 4th referral-grade gate condition. Never backfilled.'),
        ),
        migrations.AlterField(
            model_name='financialsnapshot',
            name='source',
            field=models.CharField(default='EXTRACTED', help_text='EXTRACTED (from document OCR), IRS_TEOS_XML (TEOS pipeline), MANUAL', max_length=20),
        ),
    ]
