# Generated by Django 5.2.15 on 2026-06-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0035_alter_financialsnapshot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='overreach_reviewed',
            field=models.BooleanField(default=False, help_text='Investigator acknowledged the overreach checklist at tie-off. The 4th referral-grade gate condition. Never backfilled.'),
        ),
    ]
