# Generated by Django 5.2.15 on 2026-06-22 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0036_finding_overreach_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='gate_version',
            field=models.CharField(choices=[('LEGACY_NARRATIVE', 'Legacy narrative'), ('ASSERTION_V1', 'Assertion v1')], default='ASSERTION_V1', help_text='Which referral-grade gate applies. LEGACY_NARRATIVE = grandfathered pre-Phase-4 threads (old predicate); ASSERTION_V1 = structured-assertion gate.', max_length=20),
        ),
        migrations.AddField(
            model_name='findingdocument',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='True for compatibility-index rows not authored via ThreadElementCitation (pre-Phase-4 citations, or the legacy add_document_ids path). Never reaped.'),
        ),
        migrations.CreateModel(
            name='ThreadElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('ASSERTION', 'Assertion'), ('QUESTION', 'Unresolved question'), ('NOTE', 'Context note')], max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('handoff_ready', models.BooleanField(default=False, help_text="The 'claim' flag — meaningful only on ASSERTION; gated so others cannot set it.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='investigations.finding')),
            ],
            options={
                'db_table': 'thread_element',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ThreadElementCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_reference', models.CharField(blank=True, default='', max_length=100)),
                ('context_note', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_citations', to='investigations.document')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='investigations.threadelement')),
            ],
            options={
                'db_table': 'thread_element_citation',
            },
        ),
        migrations.AddIndex(
            model_name='threadelement',
            index=models.Index(fields=['finding', 'position'], name='idx_thread_element_fp'),
        ),
        migrations.AddConstraint(
            model_name='threadelement',
            constraint=models.UniqueConstraint(fields=('finding', 'position'), name='uniq_thread_element_position'),
        ),
        migrations.AddConstraint(
            model_name='threadelementcitation',
            constraint=models.UniqueConstraint(fields=('element', 'document', 'page_reference'), name='uniq_thread_element_citation'),
        ),
    ]
