# Generated by Django 5.2.15 on 2026-06-22 17:50

from django.db import migrations

from investigations.migrations import _phase4_narrative_backfill


class Migration(migrations.Migration):
    dependencies = [
        ("investigations", "0037_finding_gate_version_findingdocument_is_legacy_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _phase4_narrative_backfill.forwards,
            _phase4_narrative_backfill.backwards,
        ),
    ]
