# Generated by Django 5.2.15 on 2026-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0038_phase4_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_INGESTED', 'Document ingested'), ('DOCUMENT_SCRUBBED', 'Document metadata scrubbed'), ('DOCUMENT_HASHED', 'Document hash computed'), ('DOCUMENT_HASH_VERIFIED', 'Document hash re-verified'), ('DOCUMENT_HASH_MISMATCH', 'Document hash mismatch detected'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_OCR_COMPLETED', 'Document OCR completed'), ('DOCUMENT_OCR_FAILED', 'Document OCR failed'), ('RECORD_CREATED', 'Record created'), ('RECORD_UPDATED', 'Record updated'), ('RECORD_DELETED', 'Record deleted'), ('SIGNAL_DETECTED', 'Signal detected'), ('SIGNAL_CONFIRMED', 'Signal confirmed'), ('SIGNAL_DISMISSED', 'Signal dismissed'), ('SIGNAL_ESCALATED', 'Signal escalated to finding'), ('FINDING_CREATED', 'Finding created'), ('FINDING_UPDATED', 'Finding updated'), ('FINDING_INCLUDED', 'Finding included in memo'), ('REFERRAL_CREATED', 'Referral created'), ('REFERRAL_SUBMITTED', 'Referral submitted'), ('REFERRAL_STATUS_CHANGED', 'Referral status changed'), ('INTAKE_REJECTED_SIZE', 'File rejected — exceeds size limit'), ('INTAKE_REJECTED_TYPE', 'File rejected — invalid MIME type'), ('INTAKE_REJECTED_CORRUPT', 'File rejected — corrupted or unreadable'), ('HASH_VERIFICATION_BATCH', 'Batch hash verification completed'), ('AI_EXTRACTION_COMPLETED', 'AI extraction completed on document'), ('AI_EXTRACTION_FAILED', 'AI extraction failed on document'), ('AI_PATTERN_RUN_COMPLETED', 'AI pattern analysis run completed'), ('AI_FINDING_CREATED', 'AI-flagged pattern written as finding'), ('AI_FINDING_REVIEWED', 'Investigator reviewed an AI-flagged finding'), ('AI_THREAD_ASSIST_COMPLETED', 'AI thread-assist proposal run completed')], help_text='Constrained action type — use AuditAction enum values only.', max_length=50),
        ),
        migrations.AlterField(
            model_name='searchjob',
            name='job_type',
            field=models.CharField(choices=[('IRS_NAME_SEARCH', 'IRS Name Search'), ('IRS_FETCH_XML', 'IRS Fetch XML'), ('OHIO_AOS', 'Ohio Auditor of State'), ('COUNTY_PARCEL', 'County Parcel Search'), ('AI_PATTERN_ANALYSIS', 'AI Pattern Analysis'), ('AI_ASK', 'AI Ask Question'), ('AI_THREAD_ASSIST', 'AI Thread Assist')], max_length=32),
        ),
    ]
